# NOTE:
# This builder configuration is NOT used to build any official binary.
# Used only for testbed tests to validate nrdot components work with core collector.

dist:
  module: github.com/newrelic/nrdot-collector-components/cmd/oteltestbedcol
  name: oteltestbedcol
  description: OpenTelemetry Collector binary for testbed only tests.
  version: 0.141.0-dev
  output_path: ./cmd/oteltestbedcol

extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.141.1-0.20251211181959-97fcd3d13b4a

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.141.1-0.20251211181959-97fcd3d13b4a
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.141.1-0.20251211181959-97fcd3d13b4a
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.141.1-0.20251211181959-97fcd3d13b4a

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.141.1-0.20251211181959-97fcd3d13b4a
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.141.1-0.20251211181959-97fcd3d13b4a

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.141.1-0.20251211181959-97fcd3d13b4a

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.47.1-0.20251211181959-97fcd3d13b4a
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.47.1-0.20251211181959-97fcd3d13b4a
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.47.1-0.20251211181959-97fcd3d13b4a
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.47.1-0.20251211181959-97fcd3d13b4a
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.47.1-0.20251211181959-97fcd3d13b4a

# When using `make genoteltestbedcol`, the `replaces` content is appended to this
# file before passing it to OCB, to ensure that local versions are used for all
# nrdot modules.
replaces:
