# NOTE:
# This builder configuration is NOT used to build any official binary.
# Used only for testbed tests to validate nrdot components work with core collector.

dist:
  module: github.com/newrelic/nrdot-collector-components/cmd/oteltestbedcol
  name: oteltestbedcol
  description: OpenTelemetry Collector binary for testbed only tests.
  version: 0.142.1-dev
  output_path: ./cmd/oteltestbedcol

extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.145.1-0.20260205185216-81bc641f26c0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.145.1-0.20260205185216-81bc641f26c0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.145.1-0.20260205185216-81bc641f26c0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.145.1-0.20260205185216-81bc641f26c0
  - gomod: github.com/newrelic/nrdot-collector-components/exporter/nopexporter v0.142.1

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.145.1-0.20260205185216-81bc641f26c0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.145.1-0.20260205185216-81bc641f26c0
  - gomod: github.com/newrelic/nrdot-collector-components/processor/adaptivetelemetryprocessor v0.142.1

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.145.1-0.20260205185216-81bc641f26c0
  - gomod: github.com/newrelic/nrdot-collector-components/receiver/nopreceiver v0.142.1

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.51.1-0.20260205185216-81bc641f26c0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.51.1-0.20260205185216-81bc641f26c0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.51.1-0.20260205185216-81bc641f26c0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.51.1-0.20260205185216-81bc641f26c0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.51.1-0.20260205185216-81bc641f26c0

# When using `make genoteltestbedcol`, the `replaces` content is appended to this
# file before passing it to OCB, to ensure that local versions are used for all
# nrdot modules.
replaces:
