# NOTE:
# This builder configuration is NOT used to build any official binary.
# To see the builder manifests used for official binaries,
# check https://github.com/open-telemetry/opentelemetry-collector-releases

dist:
  module: github.com/newrelic/nrdot-plus-collector-components/cmd/nrdotplustestbedcol
  name: nrdotplustestbedcol
  description: OpenTelemetry Collector binary for testbed only tests.
  version: 0.139.0-dev
  output_path: ./cmd/nrdotplustestbedcol

extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.139.1-0.20251105131800-09a271914bdc
  - gomod: github.com/newrelic/nrdot-plus-collector-components//extension/pprofextension v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//extension/storage/filestorage v0.139.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.139.1-0.20251105131800-09a271914bdc
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.139.1-0.20251105131800-09a271914bdc
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.139.1-0.20251105131800-09a271914bdc
  - gomod: github.com/newrelic/nrdot-plus-collector-components//exporter/carbonexporter v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//exporter/opensearchexporter v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//exporter/otelarrowexporter v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//exporter/prometheusexporter v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//exporter/sapmexporter v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//exporter/signalfxexporter v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//exporter/splunkhecexporter v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//exporter/stefexporter v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//exporter/syslogexporter v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//exporter/zipkinexporter v0.139.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.139.1-0.20251105131800-09a271914bdc
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.139.1-0.20251105131800-09a271914bdc
  - gomod: github.com/newrelic/nrdot-plus-collector-components//processor/attributesprocessor v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//processor/resourceprocessor v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//processor/transformprocessor v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//processor/filterprocessor v0.139.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.139.1-0.20251105131800-09a271914bdc
  - gomod: github.com/newrelic/nrdot-plus-collector-components//receiver/carbonreceiver v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//receiver/filelogreceiver v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//receiver/fluentforwardreceiver v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//receiver/jaegerreceiver v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//receiver/otelarrowreceiver v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//receiver/prometheusreceiver v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//receiver/signalfxreceiver v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//receiver/splunkhecreceiver v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//receiver/stefreceiver v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//receiver/syslogreceiver v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//receiver/tcplogreceiver v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//receiver/udplogreceiver v0.139.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//receiver/zipkinreceiver v0.139.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.45.1-0.20251105131800-09a271914bdc
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.45.1-0.20251105131800-09a271914bdc
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.45.1-0.20251105131800-09a271914bdc
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.45.1-0.20251105131800-09a271914bdc
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.45.1-0.20251105131800-09a271914bdc

# When using `make gennrdotplustestbedcol`, the `replaces` content is appended to this
# file before passing it to OCB, to ensure that local versions are used for all
# Contrib modules.
replaces:
