# NOTE:
# This builder configuration is used to build the New Relic Dot Collector
# with components that require CGO_ENABLED=1 (like newrelicoraclereceiver).
# For the standard collector build without CGO dependencies, see builder-config.yaml.

dist:
  module: github.com/newrelic/nrdot-collector-components/cmd/nrdotcol
  name: nrdotcol-cgo
  description: New Relic Dot Collector with CGO-enabled components.
  version: 0.142.1-dev
  output_path: ./cmd/nrdotcol

extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.142.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.142.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.142.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.142.0
  - gomod: github.com/newrelic/nrdot-collector-components/exporter/nopexporter v0.142.1

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.142.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.142.0
  - gomod: github.com/newrelic/nrdot-collector-components/processor/adaptivetelemetryprocessor v0.142.1

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.142.0
  - gomod: github.com/newrelic/nrdot-collector-components/receiver/newrelicoraclereceiver v0.142.1
  - gomod: github.com/newrelic/nrdot-collector-components/receiver/nopreceiver v0.142.1

connectors:
  - gomod: go.opentelemetry.io/collector/connector/forwardconnector v0.142.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.48.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.48.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.48.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.48.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.48.0

# When using `make gennrdotcol-cgo`, the `replaces` content is appended to this
# file before passing it to OCB, to ensure that local versions are used for all
# nrdot modules.
replaces:
