# NOTE:
# This builder configuration is used to build the New Relic Dot Collector
# for testing custom nrdot components. Only includes core collector components
# and nrdot-specific components.

dist:
  module: github.com/newrelic/nrdot-collector-components/cmd/nrdotcol
  name: nrdotcol
  description: New Relic Dot Collector with additional components.
  version: 0.141.0-dev
  output_path: ./cmd/nrdotcol

extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.142.1-0.20251217080827-1839ba7a4727

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.142.1-0.20251217080827-1839ba7a4727
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.142.1-0.20251217080827-1839ba7a4727
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.142.1-0.20251217080827-1839ba7a4727
  - gomod: github.com/newrelic/nrdot-collector-components/exporter/nopexporter v0.141.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.142.1-0.20251217080827-1839ba7a4727
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.142.1-0.20251217080827-1839ba7a4727

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.142.1-0.20251217080827-1839ba7a4727
  - gomod: github.com/newrelic/nrdot-collector-components/receiver/nopreceiver v0.141.0

connectors:
  - gomod: go.opentelemetry.io/collector/connector/forwardconnector v0.142.1-0.20251217080827-1839ba7a4727

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.48.1-0.20251217080827-1839ba7a4727
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.48.1-0.20251217080827-1839ba7a4727
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.48.1-0.20251217080827-1839ba7a4727
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.48.1-0.20251217080827-1839ba7a4727
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.48.1-0.20251217080827-1839ba7a4727

# When using `make gennrdotcol`, the `replaces` content is appended to this
# file before passing it to OCB, to ensure that local versions are used for all
# nrdot modules.
replaces:
