dist:
  module: github.com/newrelic/nrdot-plus-collector-components/cmd/nrdotpluscol
  name: nrdotpluscol
  description: Local NRDOT Plus Collector binary, testing only.
  version: v0.0.1-dev
  output_path: ./cmd/nrdotpluscol

extensions:
  - gomod: github.com/newrelic/nrdot-plus-collector-components//extension/healthcheckextension v0.128.0

exporters:
  - gomod: github.com/newrelic/nrdot-plus-collector-components/exporter/nopexporter v0.0.1
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.128.0
  - gomod: go.opentelemetry.io/collector/exporter/nopexporter v0.128.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.128.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.128.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.128.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.128.0

receivers:
  - gomod: github.com/newrelic/nrdot-plus-collector-components/receiver/nopreceiver v0.0.1
  - gomod: go.opentelemetry.io/collector/receiver/nopreceiver v0.128.0
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.128.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//receiver/kubeletstatsreceiver v0.128.0
  - gomod: github.com/newrelic/nrdot-plus-collector-components//receiver/k8sclusterreceiver v0.128.0

connectors:
  - gomod: go.opentelemetry.io/collector/connector/forwardconnector v0.128.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.34.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.34.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.34.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.34.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.34.0


# When using `make gennrdotpluscol`, the `replaces` content is appended to this
# file before passing it to OCB, to ensure that local versions are used for all
# NRDOT Plus modules.

replaces:
