dist:
  module: github.com/newrelic/nrdot-plus-collector-components/cmd/nrdotpluscol
  name: nrdotpluscol
  description: Local NRDOT Plus Collector binary, testing only.
  version: v0.0.1-dev
  output_path: ./cmd/nrdotpluscol

extensions:

exporters:
  - gomod: github.com/newrelic/nrdot-plus-collector-components/exporter/nopexporter v0.0.1
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.140.0
  - gomod: go.opentelemetry.io/collector/exporter/nopexporter v0.140.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.140.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.140.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.140.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.140.0

receivers:
  - gomod: github.com/newrelic/nrdot-plus-collector-components/receiver/nopreceiver v0.0.1
  - gomod: go.opentelemetry.io/collector/receiver/nopreceiver v0.140.0
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.140.0

connectors:
  - gomod: go.opentelemetry.io/collector/connector/forwardconnector v0.140.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.40.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.40.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.40.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.40.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.40.0


# When using `make gennrdotpluscol`, the `replaces` content is appended to this
# file before passing it to OCB, to ensure that local versions are used for all
# NRDOT Plus modules.

replaces:
