change_logs:
    api: CHANGELOG-API.md
    user: CHANGELOG.md
default_change_logs:
    - user
entries_dir: .chloggen
template_yaml: .chloggen/TEMPLATE.yaml
summary_template: .chloggen/summary.tmpl
components:
    - all
    - cmd/codecovgen
    - exporter/nopexporter
    - internal/common
    - internal/coreinternal
    - receiver/nopreceiver
    - testbed
