name: 'Update nrdot-collector-components to the latest core source'
on:
  workflow_dispatch:
  schedule:
    - cron: "27 8 * * 5" # Run at 08:27 UTC on Fridays.

permissions:
  contents: read

jobs:
  update-otel:
    permissions:
      contents: write # required for pushing changes
      pull-requests: write # required for creating PRs
      issues: write # required for creating failure issues
    runs-on: ubuntu-24.04
    if: ${{ github.repository_owner == 'newrelic' }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          path: nrdot-collector-components

      - name: Pull the latest collector repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          path: opentelemetry-collector
          repository: open-telemetry/opentelemetry-collector

      - name: Pull the latest contrib repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          path: opentelemetry-collector-contrib
          repository: open-telemetry/opentelemetry-collector-contrib

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec # v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          workdir: nrdot-collector-components

      - name: Prepare to update dependencies
        run: |
          exec > >(tee log.out) 2>&1
          LAST_COMMIT="$(git -C ./opentelemetry-collector/ rev-parse HEAD)"
          LAST_CONTRIB_COMMIT="$(git -C ./opentelemetry-collector-contrib/ rev-parse HEAD)"
          cd nrdot-collector-components
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          branch="update-otel-$(date +%s)"
          git checkout -b "$branch"
          make gennrdotcol
          make gennrdotcol-cgo
          echo "LAST_COMMIT=$LAST_COMMIT" >> "$GITHUB_ENV"
          echo "LAST_CONTRIB_COMMIT=$LAST_CONTRIB_COMMIT" >> "$GITHUB_ENV"
          echo "BRANCH_NAME=$branch" >> "$GITHUB_ENV"
      - name: Gets packages from links with retries
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          retry_wait_seconds: 1800
          timeout_minutes: 120
          max_attempts: 2
          retry_on: error
          command: |
            cd nrdot-collector-components
            make update-otel OTEL_STABLE_VERSION=${{ env.LAST_COMMIT }} OTEL_VERSION=${{ env.LAST_COMMIT }} CONTRIB_VERSION=${{ env.LAST_CONTRIB_COMMIT }}
      - name: Push and create PR
        run: |
          cd nrdot-collector-components
          git push --set-upstream origin ${{ env.BRANCH_NAME }}
          gh pr create --base main --title "[chore] Update core dependencies" --body "This PR updates the opentelemetry-collector modules to open-telemetry/opentelemetry-collector@${{ env.LAST_COMMIT }}" --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: File an issue if the workflow failed
        if: failure()
        run: |
          job_url="$(gh run view ${{ github.run_id }} -R ${{ github.repository }} --json jobs -q '.jobs[] | select(.name == "update-otel") | .url')"
          body="$(printf '[Link to job log](%s)
          
          <details>
          <summary>Last 100 lines of log</summary>

          ```
          %s
          ```
          </details>' "$job_url" "$(tail -n100 log.out | tail -c63K)")"
          gh issue create -R ${{ github.repository }} -t 'update-otel workflow failed' -b "$body" -l 'ci-cd'
        env:
          GH_TOKEN: ${{ github.token }}
